# Generated by Django 5.2.1 on 2025-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Udhiyah',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('paid', 'تم الدفع'), ('booked', 'تم حجز الأضحية'), ('slaughtered', 'تم الذبح'), ('cutting', 'تم التقطيع'), ('distributing', 'جاري التوزيع'), ('done', 'تم التوزيع')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
