# Generated by Django 5.2.1 on 2025-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udhiyah',
            name='donation_type',
            field=models.CharField(choices=[('full', 'تبرع بكامل الأضحية'), ('half', 'استلام نصفها')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='udhiyah',
            name='status',
            field=models.CharField(choices=[('paid', 'تم الدفع'), ('booked', 'تم حجز الأضحية'), ('slaughtered', 'تم الذبح'), ('cutting', 'تم التقطيع'), ('half_ready', 'نصف الأضحية جاهز للاستلام'), ('distributing', 'جاري التوزيع'), ('done', 'تم التوزيع')], max_length=20),
        ),
    ]
