# Generated by Django 5.2.1 on 2025-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_udhiyah_donation_type_alter_udhiyah_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udhiyah',
            name='status',
            field=models.CharField(choices=[('paid', 'تم الدفع'), ('booked', 'تم حجز الأضحية'), ('slaughtered', 'تم الذبح'), ('cutting', 'تم التقطيع'), ('half_ready', 'جاهز للاستلام'), ('distributing', 'جاري التوزيع'), ('done', 'تم التوزيع')], max_length=20),
        ),
    ]
